import type { Metadata } from "next";
import { Inter, Poppins } from 'next/font/google'
import Navbar from "@/components/Navbar";
import CustomCursor from "@/components/CustomCursor";
import { CursorProvider } from '@/context/CursorContext';
import "./globals.css";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <CursorProvider>
          <CustomCursor />
          <Navbar />
          <main>
            {children}
          </main>
        </CursorProvider>
      </body>
    </html>
  );
}
